### ISSUE TITLE
Margins and Paddings Not Work Correctly

### ISSUE THREAD

**Issue by askarialireza** [MahdiMajidzadeh/bootstrap-v4-rtl#15]
![untitled](https://user-images.githubusercontent.com/23168861/36350718-ff9e1c68-14b1-11e8-91a9-c8a30063ac3e.png)
When i use ml / mr or pl / pr in multi languages sites (persian/english) , elements also contains margin or padding for both directions like mx or px classes ,You must also set padding=0 or margin=0 for opposite direction. for example:

bootstrap-rtl.css:
pl {
padding-right: xxxxx !important;
padding-left: 0 !important;
}

bootstrap-original.css 
pl {
padding-left: xxxxxx;
}

**Comment by MahdiMajidzadeh** [comment]
It's an issue I aware of that, in one hand I want to keep semantic name like `pl` as `padding-left` and in another hand in multi-languages sites doesn't work well

I'm going fixed it soon

**Comment by MahdiMajidzadeh** [comment]
I fixed it in the last commit
