### ISSUE TITLE
grid offset sets margin for both sides

### ISSUE THREAD

**Issue by rastemoh** [MahdiMajidzadeh/bootstrap-v4-rtl#16]
Consider this HTML:
```
<div class="row rtl">
   <div class="col-2 offset-md-3" id="inner-div">some sample text here</div>
</div>
```
Then the #inner-div would have two margins, one from right which is correct and one from left which in inherited from the ltr bootstrap. so the latter should be removed using for example:
```
.rtl .offset-{}-x {
   margin-left: 0
}
````
Now I'm using ml-0 to fix it.
Thanks for your awesome project

**Comment by MahdiMajidzadeh** [comment]
I fixed it in the last commit
