### ISSUE TITLE
float-right and float-left rtl version

### ISSUE THREAD

**Issue by AhmadOf** [MahdiMajidzadeh/bootstrap-v4-rtl#17]
Hello,

What about the RTL version of float-{sm,md,lg,xl}-{left,right,none} classes I can't find any thing related to those classes since they are replacing the old widely used pull-left and pull-right classes

Thanks

**Comment by mostafakasem** [comment]
open the file (_rtl.scss) in .rtl( ... ) add the following mixin 

`
  @each $breakpoint in map-keys($grid-breakpoints) {
    @include media-breakpoint-up($breakpoint) {
      $infix: breakpoint-infix($breakpoint, $grid-breakpoints);
      .float#{$infix}-left  { @include float-right; }
      .float#{$infix}-right { @include float-left; }
      .float#{$infix}-none  { @include float-none; }
    }
  }`

**Comment by badrobatx01** [comment]
How to use Float-left and float-right in HTML file? I have an issue with that. it's not working for me

<div id="content" class="col-sm-4 col-md-6 float-left">
Hello World
</div>

<div id="sidebar" class="float-right">
</div>

**Comment by evilaliv3** [comment]
@MahdiMajidzadeh: In [GlobaLeaks](https://github.com/globaleaks/GlobaLeaks) we have issues as well with this.

would you please issue a realease where float-left / floatright are flipped depending on the LTR/RTL dir?

**Comment by MahdiMajidzadeh** [comment]
if I understand correctly;
you want `float-right` and `float-left` work inverse in RTL mode like padding and margin?

**Comment by progzy** [comment]
@MahdiMajidzadeh I think "float-right" should be "left" as value and "float-left", "right", no? As far as I see it does not seem to be the case in 4.6.0-3. In scss/_rtl.scss, the following would be added:

```
@each $breakpoint in map-keys($grid-breakpoints) {
  @include media-breakpoint-up($breakpoint) {
    $infix: breakpoint-infix($breakpoint, $grid-breakpoints);

    .float#{$infix}-left  { float: right !important; }
    .float#{$infix}-right { float: left !important; }
    .float#{$infix}-none  { float: none !important; }
  }
}
```
Is there any reason it was not done this way? 

Thank you.
