### ISSUE TITLE
منبع این مخزن معرفی میکنید

### ISSUE THREAD

**Issue by webineh** [MahdiMajidzadeh/bootstrap-v4-rtl#19]
سلام منبع این مخزن معرفی میکنید که در صورت به روز شدن هم ازش استفاده کنیم من خودم 2 تا راه حل دارم نمیدونم این یکی از اونهاست یا نه . چون هر دوتاشون یجایی مشکل دارن

**Comment by MahdiMajidzadeh** [comment]
منظورتون از منبع چیه
بوت استرپ اصلی بوده که من راست چینش کردم

**Comment by webineh** [comment]
خوب اگر کارخودتونه چه بهتر 

تبریک میگم

**Comment by MahdiMajidzadeh** [comment]
ممنونم
