### ISSUE TITLE
I tried to use this library in angular 5 but it doesn't work

### ISSUE THREAD

**Issue by aelkoussy** [MahdiMajidzadeh/bootstrap-v4-rtl#20]
I installed the library with npm , then added "../node_modules/bootstrap-v4-rtl/dist/css/bootstrap.min.css" in the angular cli styles (as I did with the bootstrap as normal) , but bootstrap styling is applied except the rtl part , it is still exactly similar to the normal bootstrap 4 , are there any extra steps that I missed to make it work?

(the RTL is applied to the main container div , if I remove Bootstrap from the angular cli styles it will be flipped as expected for RTL , my main problem is that in RTL in Bootstrap (the grid columns order is the same and not flipped))

Thanks

**Comment by MahdiMajidzadeh** [comment]
hi
you must use`"./node_modules/bootstrap-v4-rtl/dist/css/bootstrap-rtl.min.css"` and add class `rtl` to body or main div
