### ISSUE TITLE
Carousel doesn't cycle from right to left

### ISSUE THREAD

**Issue by Dolampochki** [MahdiMajidzadeh/bootstrap-v4-rtl#21]
Hey!
I can't figure out the RTL solution for [carousel](http://v4-alpha.getbootstrap.com/components/carousel/). [This bootstrap 3 css](https://codepen.io/dimbslmh/full/GrXpNo) fix doesn't work properly on v4 (makes white delays between a slides)

**Comment by alirezaseif28** [comment]
hi. visit this issues [github](https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/issues/55#issuecomment-916882801)
