### ISSUE TITLE
Custom Check box RTL FIX

### ISSUE THREAD

**Issue by SixSatori** [MahdiMajidzadeh/bootstrap-v4-rtl#24]
Current:
.rtl .custom-control-label::after, .rtl .custom-control-label::before {
  right: 0;
  left: inherit;
}

should be:
.rtl .custom-control-label::after, .rtl .custom-control-label::before {
  **right: -1.5rem;**
  left: inherit;
}

Non rtl original:
.custom-control-label::before {
  position: absolute;
  top: .25rem;
  **left: -1.5rem;**
  display: block;
  width: 1rem;
  height: 1rem;
  pointer-events: none;
  content: "";
  user-select: none;
  background-color: #dee2e6;
}

**Comment by Ammarzino** [comment]
Thanks, it helped.

**Comment by MahdiMajidzadeh** [comment]
can you make a pull request?
