### ISSUE TITLE
Proper RTL dropdown-menu

### ISSUE THREAD

**Issue by superware** [MahdiMajidzadeh/bootstrap-v4-rtl#26]
Shouldn't [dropdown-menu](https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/blob/v4/scss/_rtl.scss#L27):

```
.dropdown-menu {
  right: 0;
  text-align: right;
}
```

Actually be:

```
.dropdown-menu {
  left: auto !important;
  right: 0;
  text-align: right;
}
```

After this change I can get bootstrap-select to properly show in RTL.

**Comment by MahdiMajidzadeh** [comment]
thanks, fix at https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/commit/0fbba6b8483be48be4a0651128bcae4c238ccae7

**Comment by muhshahabipour** [comment]
hi, dear friend.
thanks for useful this expansion.
i develop my project with your library (latest version on npm). but i have a problem with Dropdown in RTL version. you see this problem in pictures. i don't know WHY?
can you help me?
![photo_2019-08-18_09-54-21](https://user-images.githubusercontent.com/5248892/63220506-536a9c00-c19e-11e9-9f8e-908e3179230e.jpg)
![photo_2019-08-18_09-54-17](https://user-images.githubusercontent.com/5248892/63220507-536a9c00-c19e-11e9-9185-ff9b45b25c01.jpg)
