### ISSUE TITLE
in sass not work !

### ISSUE THREAD

**Issue by vahidalvandi** [MahdiMajidzadeh/bootstrap-v4-rtl#28]
in sass not work !

**Comment by MahdiMajidzadeh** [comment]
what?

**Comment by vahidalvandi** [comment]
i used sass but not rtl !
please show real sample of use it

**Comment by kashmiry** [comment]
To use it with SASS
Just simply import the RTL version in your main scss file:
`@import "bootstrap/scss/bootstrap-rtl";`
