### ISSUE TITLE
Evaluate how to properly keep the codebase aligned with Bootstrap 4

### ISSUE THREAD

**Issue by evilaliv3** [MahdiMajidzadeh/bootstrap-v4-rtl#32]
It seems that currently the code is not aligned with the currnet bootstrap 4.

It would be great to identify a way of keeping the code aligned with the latest version of Bootstrap 4 (currently 4.2.1).

**Comment by evilaliv3** [comment]
It could by probably interesting to apply a similar approach as the one of @MohammadYounes in [RTL-bootstrap](https://github.com/MohammadYounes/RTL-bootstrap) that makes use of [rtlcss](https://github.com/MohammadYounes/rtlcss).

**Comment by MahdiMajidzadeh** [comment]
This project is created for multi languages projects that need rtl and ltr layouts. so projects likes https://github.com/MohammadYounes/RTL-bootstrap not helping

**Comment by evilaliv3** [comment]
@MahdiMajidzadeh: could you please clarify about your comment?

RTL-bootstrap using rtlcss is a package that make it possible to use bootstrap 3 with both rtl and ltr.

I see that you are doing the same kind of project but for bootstrap 4; what i misunderstood?

thank you!

**Comment by MohammadYounes** [comment]
@evilaliv3 Bootstrap 4 RTL is available here https://rtlcss.com/cdn/css-frameworks/bootstrap/

**Comment by evilaliv3** [comment]
You always rock maaan! Thank you!
