### ISSUE TITLE
Release new fixes to npm

### ISSUE THREAD

**Issue by walidbagh** [MahdiMajidzadeh/bootstrap-v4-rtl#33]
Hey, i want to thank you for efforts in this package :D 
I noticed that since the last release (9 months ago), you committed 3 fixes, but i can't get them via NPM because you haven't made a release of them... 
Can you please make a new release and push it to npm ? I would be grateful :)

**Comment by MahdiMajidzadeh** [comment]
done, v4.3.1 is online now
