### ISSUE TITLE
jQuery missed from peerDependencies

### ISSUE THREAD

**Issue by ybelenko** [MahdiMajidzadeh/bootstrap-v4-rtl#34]
Original Bootstrap repo requires jQuery
```json
  "dependencies": {},
  "peerDependencies": {
    "jquery": "1.9.1 - 3",
    "popper.js": "^1.14.3"
  },
  "devDependencies": {
```

while current repo does not
https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/blob/5baf102886084cef8c29bd082cf80fcea5938e11/package.json#L81-L85

How is this possible? Is `package.json` simply outdated from original repo?

**Comment by MahdiMajidzadeh** [comment]
at latest version of bootstrap it's removed -> https://github.com/twbs/bootstrap/blob/master/package.json
