### ISSUE TITLE
form-check class not RTL

### ISSUE THREAD

**Issue by rhalaly** [MahdiMajidzadeh/bootstrap-v4-rtl#35]
The definition of `form-check` contains `padding-left` but have no RTL fix
```
.form-check {
    position: relative;
    display: block;
    padding-left: 1.25rem;
}
```

The RTL version should include `padding-right` instead.

**Comment by mortezakarimi** [comment]
This bug fixed in https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/pull/43/commits/1fe410ec00073fb4c3d3818af0850f9f2fd85718
