### ISSUE TITLE
Question : How Add Bootstrap RTL 

### ISSUE THREAD

**Issue by fakhamatia** [MahdiMajidzadeh/bootstrap-v4-rtl#37]
Hi
Thanks for great work.
How How Add Bootstrap RTL properly ?
First add original Bootstrap CSS and second RTL CSS ? Or just RTL CSS ? How about JS ?
And i have to add `rtl` to every tag in document for RTL ?

**Comment by MahdiMajidzadeh** [comment]
hi
just rtl css file is enough and just add rtl class to body tag
js file not modified and you can use original js file.
