### ISSUE TITLE
Padding issue

### ISSUE THREAD

**Issue by fakhamatia** [MahdiMajidzadeh/bootstrap-v4-rtl#38]
When i use pr-0 or pl-0 , bootstrap set both right and left padding 0
`.pr-0,[dir=rtl] .pr-0{padding-right:0!important;padding-left:0!important}.rtl
 .pl-0,[dir=rtl] .pl-0{padding-left:0!important;padding-right:0!important}.rtl `
Why when padding right is 0 , padding left 0 ? just right must be 0

![Screenshot from 2019-05-13 17-34-20](https://user-images.githubusercontent.com/20030910/57624144-90733100-75a6-11e9-9bef-0fd2b0a94a2b.png)

this is happening for other p classes
`.pl-5,[dir=rtl] .pl-5{padding-left:0!important;padding-right:3rem!important}.rtl`
its pl-5 but padding left is 0 and padding right is 3rem

**Comment by rishpandey** [comment]
I'm still facing this. Any workaround?
