### ISSUE TITLE
breadcrumb

### ISSUE THREAD

**Issue by hamedasgari88** [MahdiMajidzadeh/bootstrap-v4-rtl#39]
.breadcrumb-item+.breadcrumb-item {
    padding-left: .5rem; --> padding-right: .5rem;
}

.breadcrumb-item+.breadcrumb-item::before {
    display: inline-block;
    padding-right: .5rem; --> padding-left: .5rem;
    color: #6c757d;
    content: "/";
}

**Comment by hamedasgari88** [comment]
.rtl .text-right, [dir=rtl] .text-right {
    text-align: left!important;
}

right == left  ?
left == right  ?

**Comment by MahdiMajidzadeh** [comment]
can you explain more about breadcrumb?

[bootstrap-v4-rtl](https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl) designed for multi languages project and by adding `rtl` class all page get rtl. for that, every right == left and left == right

**Comment by mortezakarimi** [comment]
This bug fixed in https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/commit/9135a07169d3c9baa8b32a4461e8a5b3eaccc118
