### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by reza-Abdollahi** [MahdiMajidzadeh/bootstrap-v4-rtl#45]
Unrecognised input. Possibly missing opening '{'
      in /Files/Projects/myproject/node_modules/bootstrap-v4-rtl/dist/css/bootstrap-rtl.min.css (line 6, column 757)
ℹ ｢wdm｣: Failed to compile.

**Comment by MahdiMajidzadeh** [comment]
can you check again with [lastest version](https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/releases/tag/v4.0.3-5)?

**Comment by reza-Abdollahi** [comment]
I solved my problem by using the file directly and avoiding it from going into the less compiler pipeline (by introducing a new separate rule for Less files in Webpack configuration)
