### ISSUE TITLE
bootstrap-v4-rtl/scss/_navbar.scss:46

### ISSUE THREAD

**Issue by pmpr** [MahdiMajidzadeh/bootstrap-v4-rtl#46]
`.navbar-brand` has a `margin-right` (should be `margin-left`). Is this package, made manually or by using automated tools such as [rtlcss](https://rtlcss.com/index.html) ? why such problems exists inside the package?

**Comment by MahdiMajidzadeh** [comment]
this package designed to used in multi-languages sites and all page layout turn into rtl just by adding `rtl` class to body tag, so left and right is reversed when layout is in rtl direction
