### ISSUE TITLE
Problem with dropdown-menu

### ISSUE THREAD

**Issue by muhshahabipour** [MahdiMajidzadeh/bootstrap-v4-rtl#49]
hi, dear friend.
thanks for this helpful expansion.
i know maybe this issue has been duplicate (https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/issues/26#issue-385831150) but i develop my project with your library (latest version on npm), i have a problem with Dropdown in RTL version. you see this problem in pictures. i don't know WHY?
can you help me?
![1](https://user-images.githubusercontent.com/5248892/63330871-d11edb00-c349-11e9-9477-c4b90cce63eb.jpg)
![2](https://user-images.githubusercontent.com/5248892/63330873-d1b77180-c349-11e9-8a61-542ed80de326.jpg)

**Comment by MahdiMajidzadeh** [comment]
I added drowpdown to demo and it's fine
 are you using latest version?

![image](https://user-images.githubusercontent.com/6115476/65815537-a738be00-e1fd-11e9-987b-25389ed64d09.png)

**Comment by muhshahabipour** [comment]
thank you for your attention to this matter, i solved by add `data-boundary="viewport"` and change css `left and right` in rtl class.
