### ISSUE TITLE
Not working with Bootstrap v4.0.0-beta.2

### ISSUE THREAD

**Issue by babakarj** [MahdiMajidzadeh/bootstrap-v4-rtl#5]
Having **Bootstrap v4.0.0-beta.2** and copy `bootstrap-rtl.css` in `bootstrap.css` folder. And here are the references:
```html
<link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
<link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
<link href="~/lib/bootstrap/css/bootstrap-rtl.css" rel="stylesheet" />
```
But nothing happened and no changes in directions. Should I make any other changes?

**Comment by MahdiMajidzadeh** [comment]
first, you do not need `bootstrap.css`, `bootstrap-rtl.css` contain it.
second, you must add `rtl` class to your `<body>` or your main wrapper element

```
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap-rtl.css" rel="stylesheet" />
</head>
<body class='rtl'>
    ...
