### ISSUE TITLE
rtl not working in angular carousel

### ISSUE THREAD

**Issue by sunn789** [MahdiMajidzadeh/bootstrap-v4-rtl#55]
Hi, 
I add this version of bootstrap rtl in angular project, it work fine in normal condition but if i want to use ng-bootstrap carousel the pictures move to the right side of page and don't show, how can i fix it?
for test i remove rtl bootsatrp from angular. json then carousel work fine

**Comment by MahdiMajidzadeh** [comment]
can you check if add `direction:ltr` to parent of caroucel its work or not?

**Comment by sunn789** [comment]
its not work
I create my caruousel in new component set direction for app-carousel or for div in home that is parent of that but not working

**Comment by MahdiMajidzadeh** [comment]
I'm sorry but I do not know very nush about angular

**Comment by alirezaseif28** [comment]
you add in index.html class rtl look like `<body class="rtl">`
