### ISSUE TITLE
Please add npm version

### ISSUE THREAD

**Issue by aliqasemzadeh** [MahdiMajidzadeh/bootstrap-v4-rtl#7]
Hello,
Please add npm version.

**Comment by aliqasemzadeh** [comment]
We are waiting for NPM version.

**Comment by MahdiMajidzadeh** [comment]
NPMpackage name taken by someone else, I tried to take package name and it's take some time

**Comment by ahmadalli** [comment]
@MahdiMajidzadeh can't you publish using a different name?
@AGhasemzadeh you can use yarn `yarn add https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl` and it'll add `bootstrap` package to your project

**Comment by ahmadalli** [comment]
also, you can edit `package.json` file with proper info so yarn don't confuse it with actual npm package :) @MahdiMajidzadeh

**Comment by MahdiMajidzadeh** [comment]
publish with a different name  not very professional, I will wait for npm make package name available.

**Comment by MahdiMajidzadeh** [comment]
done
