### ISSUE TITLE
Text align left/right?

### ISSUE THREAD

**Issue by fisharebest** [MahdiMajidzadeh/bootstrap-v4-rtl#8]
https://github.com/MahdiMajidzadeh/bootstrap-v4-rtl/blob/v4.0.0-beta/dist/css/bootstrap-rtl.css#L126

```
body {
  ...
  text-align: left;
  ...
}
```

Should this be `text-align: right;`?

**Comment by fahamidev** [comment]
Yes, do the same

**Comment by MahdiMajidzadeh** [comment]
did you add `rtl` class to your `<body>` tag?

**Comment by fisharebest** [comment]
>did you add `rtl` class to your `<body>` tag?

I added it to the `<html>` tag.  e.g. `<html lang="ar" dir="rtl" class="rtl">`.

But I am now using http://cssjanus.github.io/ to automatically create a bootstrap-rtl.css file from bootstrap.css.

So if you cannot reproduce the problem, please close this issue.
